#include "list.h"
#include "bin_tree.h"

int main() {
  printf("%s\n", "list #1");
  L_NODE* l1 = NULL;
  l1 = insert_back_iter(l1, 2);
  l1 = insert_back_iter(l1, 4);
  l1 = insert_back_iter(l1, 6);
  l1 = insert_back_iter(l1, 8);
  l1 = insert_back_iter(l1, 10);
  l1 = insert_back_iter(l1, 12);
  l1 = insert_back_iter(l1, 14);
  L_NODE* nd = node_at_ind(l1, 7);
  if (nd) {
    printf("%d\n", nd -> key);
  }
  print_rec(l1);
  puts("\n");

  printf("%s\n", "list #2");
  L_NODE* l2 = NULL;
  l2 = insert_back_rec(l2, 3);
  l2 = insert_back_rec(l2, 8);
  l2 = insert_back_rec(l2, 10);
  l2 = insert_back_rec(l2, 18);
  l2 = insert_back_rec(l2, 20);
  l2 = insert_back_rec(l2, 30);
  l2 = insert_back_rec(l2, 40);
  printf("%d\n", lin_search_iter(l2, 8));
  print_rec(l2);
  puts("\n");

  printf("%s\n", "list #3");
  L_NODE* l3 = NULL;
  l3 = insert_front(l3, 1024);
  l3 = insert_front(l3, 512);
  l3 = insert_front(l3, 256);
  l3 = insert_front(l3, 128);
  l3 = insert_front(l3, 64);
  l3 = insert_front(l3, 32);
  l3 = insert_front(l3, 16);
  print_rec(l3);
  puts("\n");

  printf("%s\n", "list #4");
  L_NODE* l4 = NULL;
  l4 = insert_iter(l4, 200, 0);
  l4 = insert_iter(l4, 199, 0);
  l4 = insert_iter(l4, 198, 0);
  print_rec(l4);
  putchar('\n');
  l4 = insert_iter(l4, 201, 1);
  print_rec(l4);
  putchar('\n');
  l4 = insert_iter(l4, 250, 2);
  print_rec(l4);
  putchar('\n');
  l4 = insert_iter(l4, 300, 5);
  print_rec(l4);
  putchar('\n');
  l4 = insert_iter(l4, 315, 15);
  print_rec(l4);
  putchar('\n');
  l4 = insert_iter(l4, 99, 3);
  print_rec(l4);
  putchar('\n');
  l4 = insert_iter(l4, 299, 8);
  print_rec(l4);
  putchar('\n');
  bubble_sort(l4);
  print_rec(l4);
  puts("\n");

  printf("%s\n", "list #5");
  L_NODE* l5 = NULL;
  l5 = insert_rec(l5, 200, 0);
  l5 = insert_rec(l5, 199, 0);
  l5 = insert_rec(l5, 198, 0);
  print_rec(l5);
  putchar('\n');
  l5 = insert_rec(l5, 100, 1);
  print_rec(l5);
  putchar('\n');
  l5 = insert_rec(l5, 150, 3);
  print_rec(l5);
  putchar('\n');
  l5 = insert_rec(l5, 300, 16);
  print_rec(l5);
  bubble_sort(l5);
  putchar('\n');
  print_rec(l5);
  puts("\n");

  printf("%s\n", "list #6");
  L_NODE* l6 = NULL;
  l6 = insert_rec(l6, 10, 0);
  l6 = insert_rec(l6, 9, 0);
  l6 = insert_rec(l6, 8, 0);
  l6 = insert_rec(l6, 15, 1);
  l6 = insert_rec(l6, 14, 3);
  l6 = insert_rec(l6, 13, 5);
  print_rec(l6);
  putchar('\n');
  l6 = remove_iter(l6, 0);
  print_rec(l6);
  putchar('\n');
  l6 = remove_iter(l6, 2);
  print_rec(l6);
  putchar('\n');
  l6 = remove_iter(l6, 3);
  print_rec(l6);
  putchar('\n');
  l6 = remove_iter(l6, 0);
  print_rec(l6);
  putchar('\n');
  l6 = remove_iter(l6, 0);
  print_rec(l6);
  puts("\n");

  printf("%s\n", "tree #1");
  T_NODE* r = NULL;
  r = bst_insert_iter(r, 20);
  r = bst_insert_iter(r, 15);
  r = bst_insert_iter(r, 25);
  r = bst_insert_iter(r, 29);
  print_tree(r);
  putchar('\n');
  printf("height: %d\n\n", height(r));
  printf("sum of keys: %d\n\n", sum_keys(r));
  T_NODE* min = minimum_rec(r);
  if (min) {
    printf("%d\n", min -> key);
  }
  puts("\n");

  printf("%s\n", "tree #2");
  T_NODE* r1 = NULL;
  r1 = bst_insert_iter(r1, 20);
  r1 = bst_insert_iter(r1, 15);
  r1 = bst_insert_iter(r1, 25);
  r1 = bst_insert_iter(r1, 39);
  r1 = bst_insert_iter(r1, -2);
  r1 = bst_insert_iter(r1, -1);
  r1 = bst_insert_iter(r1, 41);
  r1 = bst_insert_iter(r1, 23);
  r1 = bst_insert_iter(r1, 40);
  print_tree(r1);
  putchar('\n');
  min = minimum_rec(r1);
  if (min) {
    printf("%d\n", min -> key);
  }
  puts("\n");

  printf("%s\n", "tree #3");
  T_NODE* r2 = NULL;
  printf("height: %d\n", height(r2));
  r2 = (T_NODE*) malloc(sizeof(T_NODE));
  r2 -> key = 3;
  r2 -> left = NULL;
  r2 -> right = NULL;
  printf("height: %d\n", height(r2));
  T_NODE* n1 = (T_NODE*) malloc(sizeof(T_NODE));
  n1 -> key = 8;
  n1 -> left = NULL;
  n1 -> right = NULL;
  r2 -> left = n1;
  printf("height: %d\n", height(r2));
  T_NODE* n2 = (T_NODE*) malloc(sizeof(T_NODE));
  n2 -> key = 68;
  n2 -> left = NULL;
  n2 -> right = NULL;
  n1 -> left = n2;
  printf("height: %d\n", height(r2));
  T_NODE* n3 = (T_NODE*) malloc(sizeof(T_NODE));
  n3 -> key = 64;
  n3 -> left = NULL;
  n3 -> right = NULL;
  r2 -> right = n3;
  printf("height: %d\n", height(r2));
  T_NODE* n4 = (T_NODE*) malloc(sizeof(T_NODE));
  n4 -> key = 14;
  n4 -> left = NULL;
  n4 -> right = NULL;
  n3 -> right = n4;
  printf("height: %d\n", height(r2));
  T_NODE* n5 = (T_NODE*) malloc(sizeof(T_NODE));
  n5 -> key = 14;
  n5 -> left = NULL;
  n5 -> right = NULL;
  n4 -> left = n5;
  printf("height: %d\n", height(r2));
  T_NODE* n6 = (T_NODE*) malloc(sizeof(T_NODE));
  n6 -> key = 24;
  n6 -> left = NULL;
  n6 -> right = NULL;
  n5 -> left = n6;
  printf("height: %d\n", height(r2));
  T_NODE* n7 = (T_NODE*) malloc(sizeof(T_NODE));
  n7 -> key = 44;
  n7 -> left = NULL;
  n7 -> right = NULL;
  n2 -> left = n7;
  printf("height: %d\n", height(r2));
  T_NODE* n8 = (T_NODE*) malloc(sizeof(T_NODE));
  n8 -> key = 134;
  n8 -> left = NULL;
  n8 -> right = NULL;
  n7 -> left = n8;
  printf("height: %d\n", height(r2));
  T_NODE* n9 = (T_NODE*) malloc(sizeof(T_NODE));
  n9 -> key = 234;
  n9 -> left = NULL;
  n9 -> right = NULL;
  n8 -> right = n9;
  printf("height: %d\n", height(r2));
  puts("\n");
  print_tree(r2);
  puts("\n");

  printf("%s\n", "tree #4");
  T_NODE* r3 = NULL;
  printf("%d\n", verify_BST(r3));
  r3 = (T_NODE*) malloc(sizeof(T_NODE));
  r3 -> key = 15;
  r3 -> left = NULL;
  r3 -> right = NULL;
  printf("%d\n", verify_BST(r3));
  T_NODE* r3_1 = (T_NODE*) malloc(sizeof(T_NODE));
  r3_1 -> key = 10;
  r3_1 -> left = NULL;
  r3_1 -> right = NULL;
  r3 -> left = r3_1;
  printf("%d\n", verify_BST(r3));
  T_NODE* r3_2 = (T_NODE*) malloc(sizeof(T_NODE));
  r3_2 -> key = 20;
  r3_2 -> left = NULL;
  r3_2 -> right = NULL;
  r3 -> right = r3_2;
  printf("%d\n", verify_BST(r3));
  T_NODE* r3_4 = (T_NODE*) malloc(sizeof(T_NODE));
  r3_4 -> key = 20;
  r3_4 -> left = NULL;
  r3_4 -> right = NULL;
  r3_2 -> left = r3_4;
  printf("%d\n", verify_BST(r3));
  printf("%d\n", count_nodes(r3));
  puts("\n");

  printf("%s\n", "tree #5");
  T_NODE* r4 = NULL;
  r4 = bst_parent_insert_iter(r4, 6);
  print_tree(r4);
  putchar('\n');
  r4 = bst_parent_insert_iter(r4, 9);
  print_tree(r4);
  putchar('\n');
  r4 = bst_parent_insert_iter(r4, 2);
  print_tree(r4);
  putchar('\n');
  r4 = bst_parent_insert_iter(r4, -1);
  print_tree(r4);
  putchar('\n');
  r4 = bst_parent_insert_iter(r4, 11);
  print_tree(r4);
  putchar('\n');
  r4 = bst_parent_insert_iter(r4, 8);
  print_tree(r4);
  putchar('\n');
  r4 = bst_parent_insert_iter(r4, 16);
  print_tree(r4);
  putchar('\n');
  r4 = bst_parent_insert_iter(r4, 6);
  print_tree(r4);
  putchar('\n');
  printf("### %d\n", r4 -> right -> left -> parent -> parent ->  key);
  T_NODE* s = successor(r4, r4 -> right -> right -> right);
  if (s) {
    printf("*** %d\n", s -> key);
  }
  puts("\n");

  printf("%s\n", "doubly-linked list #1");
  L_NODE_D* dl1 = NULL;

  dl1 = insert_back_iter_d(dl1, 0);
  dl1 = insert_back_iter_d(dl1, 1);
  dl1 = insert_back_iter_d(dl1, 1);
  dl1 = insert_back_iter_d(dl1, 2);
  dl1 = insert_back_iter_d(dl1, 3);
  dl1 = insert_back_iter_d(dl1, 5);
  L_NODE_D* tail = dl1 -> next -> next -> next -> next -> next;
  printf("%d ", tail -> key);
  printf("%d ", tail -> prev -> key);
  printf("%d ", tail -> prev -> prev -> key);
  printf("%d ", tail -> prev -> prev -> prev -> key);
  printf("%d ", tail -> prev -> prev -> prev -> prev -> key);
  printf("%d ", tail -> prev -> prev -> prev -> prev -> prev -> key);
  puts("\n");
}
