#include <stdio.h>
int
main ()
{
  char data[30000] = { 0 };
  int data_pointer = 0;
  data[data_pointer]++;
  data[data_pointer]++;
  data[data_pointer]++;
  data[data_pointer]++;
  data[data_pointer]++;
  data[data_pointer]++;
  data[data_pointer]++;
  data[data_pointer]++;
  data[data_pointer]++;
  data[data_pointer]++;
  data[data_pointer]++;
  data[data_pointer]++;
  data[data_pointer]++;
  data[data_pointer]++;
  data[data_pointer]++;
  data[data_pointer]++;
  data[data_pointer]++;
  data[data_pointer]++;
  data[data_pointer]++;
  data[data_pointer]++;
  data[data_pointer]++;
  data[data_pointer]++;
  data[data_pointer]++;
  data[data_pointer]++;
  data[data_pointer]++;
  data[data_pointer]++;
  data[data_pointer]++;
  data[data_pointer]++;
  data[data_pointer]++;
  data[data_pointer]++;
  data[data_pointer]++;
  data[data_pointer]++;
  data[data_pointer]++;
  data[data_pointer]++;
  data[data_pointer]++;
  data[data_pointer]++;
  data[data_pointer]++;
  data[data_pointer]++;
  data[data_pointer]++;
  data[data_pointer]++;
  data[data_pointer]++;
  data[data_pointer]++;
  data[data_pointer]++;
  data[data_pointer]++;
  data[data_pointer]++;
  data[data_pointer]++;
  data[data_pointer]++;
  data[data_pointer]++;
  data[data_pointer]++;
  data[data_pointer]++;
  data[data_pointer]++;
  data[data_pointer]++;
  data[data_pointer]++;
  data[data_pointer]++;
  data[data_pointer]++;
  data[data_pointer]++;
  data[data_pointer]++;
  data[data_pointer]++;
  data[data_pointer]++;
  data[data_pointer]++;
  data[data_pointer]++;
  data[data_pointer]++;
  data[data_pointer]++;
  data[data_pointer]++;
  data[data_pointer]++;
  data[data_pointer]++;
  data[data_pointer]++;
  data[data_pointer]++;
  data[data_pointer]++;
  data_pointer++;
  data[data_pointer]++;
  data[data_pointer]++;
  data[data_pointer]++;
  while (data[data_pointer])
    {
      data[data_pointer]--;
      data_pointer--;
      printf ("%c", (data[data_pointer]));
      data_pointer++;
    }
  return 0;
}
