#include <stdio.h>
#include <stdbool.h>

int main() {
  bool P, Q, R, Y;
  puts("P AND (Q OR R)");
  printf("P\tQ\tR\tY\n");

  P = false;
  Q = false;
  R = false;
  Y = P && (Q || R);
  printf("%c\t%c\t%c\t", P ? 'T' : 'F', Q ? 'T' : 'F', R ? 'T' : 'F');
  printf("%c\n", Y ? 'T' : 'F');
  P = false;
  Q = false;
  R = true;
  Y = P && (Q || R);
  printf("%c\t%c\t%c\t", P ? 'T' : 'F', Q ? 'T' : 'F', R ? 'T' : 'F');
  printf("%c\n", Y ? 'T' : 'F');
  P = false;
  Q = true;
  R = false;
  Y = P && (Q || R);
  printf("%c\t%c\t%c\t", P ? 'T' : 'F', Q ? 'T' : 'F', R ? 'T' : 'F');
  printf("%c\n", Y ? 'T' : 'F');
  P = false;
  Q = true;
  R = true;
  Y = P && (Q || R);
  printf("%c\t%c\t%c\t", P ? 'T' : 'F', Q ? 'T' : 'F', R ? 'T' : 'F');
  printf("%c\n", Y ? 'T' : 'F');
  P = true;
  Q = false;
  R = false;
  Y = P && (Q || R);
  printf("%c\t%c\t%c\t", P ? 'T' : 'F', Q ? 'T' : 'F', R ? 'T' : 'F');
  printf("%c\n", Y ? 'T' : 'F');
  P = true;
  Q = false;
  R = true;
  Y = P && (Q || R);
  printf("%c\t%c\t%c\t", P ? 'T' : 'F', Q ? 'T' : 'F', R ? 'T' : 'F');
  printf("%c\n", Y ? 'T' : 'F');
  P = true;
  Q = true;
  R = false;
  Y = P && (Q || R);
  printf("%c\t%c\t%c\t", P ? 'T' : 'F', Q ? 'T' : 'F', R ? 'T' : 'F');
  printf("%c\n", Y ? 'T' : 'F');
  P = true;
  Q = true;
  R = true;
  Y = P && (Q || R);
  printf("%c\t%c\t%c\t", P ? 'T' : 'F', Q ? 'T' : 'F', R ? 'T' : 'F');
  printf("%c\n", Y ? 'T' : 'F');

  putchar('\n');
  puts("(P AND Q) OR (P AND R)");
  printf("P\tQ\tR\tY\n");

  P = false;
  Q = false;
  R = false;
  Y = (P && Q) || (P && R);
  printf("%c\t%c\t%c\t", P ? 'T' : 'F', Q ? 'T' : 'F', R ? 'T' : 'F');
  printf("%c\n", Y ? 'T' : 'F');
  P = false;
  Q = false;
  R = true;
  Y = (P && Q) || (P && R);
  printf("%c\t%c\t%c\t", P ? 'T' : 'F', Q ? 'T' : 'F', R ? 'T' : 'F');
  printf("%c\n", Y ? 'T' : 'F');
  P = false;
  Q = true;
  R = false;
  Y = (P && Q) || (P && R);
  printf("%c\t%c\t%c\t", P ? 'T' : 'F', Q ? 'T' : 'F', R ? 'T' : 'F');
  printf("%c\n", Y ? 'T' : 'F');
  P = false;
  Q = true;
  R = true;
  Y = (P && Q) || (P && R);
  printf("%c\t%c\t%c\t", P ? 'T' : 'F', Q ? 'T' : 'F', R ? 'T' : 'F');
  printf("%c\n", Y ? 'T' : 'F');
  P = true;
  Q = false;
  R = false;
  Y = (P && Q) || (P && R);
  printf("%c\t%c\t%c\t", P ? 'T' : 'F', Q ? 'T' : 'F', R ? 'T' : 'F');
  printf("%c\n", Y ? 'T' : 'F');
  P = true;
  Q = false;
  R = true;
  Y = (P && Q) || (P && R);
  printf("%c\t%c\t%c\t", P ? 'T' : 'F', Q ? 'T' : 'F', R ? 'T' : 'F');
  printf("%c\n", Y ? 'T' : 'F');
  P = true;
  Q = true;
  R = false;
  Y = (P && Q) || (P && R);
  printf("%c\t%c\t%c\t", P ? 'T' : 'F', Q ? 'T' : 'F', R ? 'T' : 'F');
  printf("%c\n", Y ? 'T' : 'F');
  P = true;
  Q = true;
  R = true;
  Y = (P && Q) || (P && R);
  printf("%c\t%c\t%c\t", P ? 'T' : 'F', Q ? 'T' : 'F', R ? 'T' : 'F');
  printf("%c\n", Y ? 'T' : 'F');
}
